[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@v2-periphery/contracts/=lib/v2-periphery/contracts/',
  '@v2-core/contracts/=lib/v2-core/contracts/',
  '@v3-core/contracts/=lib/v3-core/contracts/',
  '@v3-periphery/contracts/=lib/v3-periphery/contracts/',
  '@solmate/src/=lib/solmate/src/'
]